# Git.Clone
git clone https:// ... .git

git clone 
git clone ...
git clone https://...
git clone https://... .git
git clone https:// ... .git
git clone 📁https://...
git clone 🌐https://...
git clone 🌎https://...